export const startingPostions = [
    { position: "a8", name: "black-rook", isFirstMove: true },
    { position: "e8", name: "black-king", isFirstMove: true },
    { position: "h8", name: "black-rook", isFirstMove: true },
    { position: "a7", name: "black-pawn", isFirstMove: true },
    { position: "b7", name: "black-pawn", isFirstMove: true },
    { position: "c7", name: "black-pawn", isFirstMove: true },
    { position: "d7", name: "black-pawn", isFirstMove: true },
    { position: "e7", name: "black-pawn", isFirstMove: true },
    { position: "f7", name: "black-pawn", isFirstMove: true },
    { position: "g7", name: "black-pawn", isFirstMove: true },
    { position: "h7", name: "black-pawn", isFirstMove: true },
    { position: "a1", name: "white-rook", isFirstMove: true },
    { position: "e1", name: "white-king", isFirstMove: true },
    { position: "h1", name: "white-rook", isFirstMove: true },
    { position: "a2", name: "white-pawn", isFirstMove: true },
    { position: "b2", name: "white-pawn", isFirstMove: true },
    { position: "c2", name: "white-pawn", isFirstMove: true },
    { position: "d2", name: "white-pawn", isFirstMove: true },
    { position: "e2", name: "white-pawn", isFirstMove: true },
    { position: "f2", name: "white-pawn", isFirstMove: true },
    { position: "g2", name: "white-pawn", isFirstMove: true },
    { position: "h2", name: "white-pawn", isFirstMove: true }
];